# -*- coding: utf-8 -*-
"""plot_bars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TtFdr52Ee9p4YsXOKv7W-yI5HL5RvZRY

**Import Libraries**
"""

# import libraries
import matplotlib.pyplot as plt
import csv

"""**Read csv files and Store results**"""

# read csv files and store results
results = {}

files = ["timings_exp1.csv", "timings_exp2_run1.csv"]

for file_name in files:
    with open(file_name, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            results[row["experiment"]] = int(row["runtime_seconds"])

# reuse same configs
results["W-1"] = results.get("W-1", results["H-1"])
results["V-2"] = results.get("V-2", results["H-3"])

print(results)

"""**Horizontal Scaling Plot**"""

# horizontal scaling plot
def plot_horizontal_scaling(results):

    workers = [1, 2, 3]
    times = [results["H-1"], results["H-2"], results["H-3"]]

    # compute speedup
    T1 = times[0]
    speedup = [T1 / t for t in times]
    ideal = [1, 2, 3]

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    fig.suptitle("Horizontal Scaling (5 GB)")

    # runtime plot
    bars = axes[0].bar(workers, times, color='steelblue')
    axes[0].bar_label(bars)
    axes[0].set_title("Runtime vs Workers")
    axes[0].set_xlabel("Workers")
    axes[0].set_ylabel("Time (sec)")
    axes[0].set_xticks(workers)
    axes[0].grid(axis='y')

    # speedup plot
    axes[1].plot(workers, speedup, 'o-', label='Actual')
    axes[1].plot(workers, ideal, 's--', label='Ideal')
    axes[1].set_title("Speedup vs Ideal")
    axes[1].set_xlabel("Workers")
    axes[1].set_ylabel("Speedup")
    axes[1].legend()
    axes[1].grid()

    plt.tight_layout()
    plt.savefig("horizontal_scaling.png", dpi=300, bbox_inches='tight')
    plt.show()

plot_horizontal_scaling(results)

"""**Vertical Scaling Plot (5GB)**"""

# vertical scaling plot (5 GB)
def plot_vertical_scaling_5gb(results):

    cores = [1, 2]
    times = [results["V-1"], results["V-2"]]

    # compute speedup
    T1 = times[0]
    speedup = [T1 / t for t in times]
    ideal = [1, 2]

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    fig.suptitle("Vertical Scaling (5 GB)")

    # runtime plot
    bars = axes[0].bar(cores, times, color='orange')
    axes[0].bar_label(bars)
    axes[0].set_title("Runtime vs Cores")
    axes[0].set_xlabel("Cores")
    axes[0].set_ylabel("Time (sec)")
    axes[0].set_xticks(cores)
    axes[0].grid(axis='y')

    # speedup plot
    axes[1].plot(cores, speedup, 'o-', label='Actual')
    axes[1].plot(cores, ideal, 's--', label='Ideal')
    axes[1].set_title("Speedup vs Ideal")
    axes[1].set_xlabel("Cores")
    axes[1].set_ylabel("Speedup")
    axes[1].legend()
    axes[1].grid()

    plt.tight_layout()
    plt.savefig("vertical_scaling_5gb.png", dpi=300, bbox_inches='tight')
    plt.show()

plot_vertical_scaling_5gb(results)

"""**Vertical Scaling Plot (10GB)**"""

# vertical scaling plot (10 GB)
def plot_vertical_scaling_10gb(results):

    cores = [1, 2]
    times = [results["V-3"], results["V-4"]]

    # compute speedup
    T1 = times[0]
    speedup = [T1 / t for t in times]
    ideal = [1, 2]

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    fig.suptitle("Vertical Scaling (10 GB)")

    # runtime plot
    bars = axes[0].bar(cores, times, color='orange')
    axes[0].bar_label(bars)
    axes[0].set_title("Runtime vs Cores")
    axes[0].set_xlabel("Cores")
    axes[0].set_ylabel("Time (sec)")
    axes[0].set_xticks(cores)
    axes[0].grid(axis='y')

    # speedup plot
    axes[1].plot(cores, speedup, 'o-', label='Actual')
    axes[1].plot(cores, ideal, 's--', label='Ideal')
    axes[1].set_title("Speedup vs Ideal")
    axes[1].set_xlabel("Cores")
    axes[1].set_ylabel("Speedup")
    axes[1].legend()
    axes[1].grid()

    plt.tight_layout()
    plt.savefig("vertical_scaling_10gb.png", dpi=300, bbox_inches='tight')
    plt.show()

plot_vertical_scaling_10gb(results)

"""**Weak Scaling Plot**"""

# weak scaling plot
def plot_weak_scaling(results):

    workers = [1, 2]
    times = [results["W-1"], results["W-2"]]

    # ideal runtime stays constant
    ideal = [times[0], times[0]]

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    fig.suptitle("Weak Scaling")

    # runtime plot
    bars = axes[0].bar(workers, times, color='green')
    axes[0].bar_label(bars)
    axes[0].set_title("Runtime vs Workers")
    axes[0].set_xlabel("Workers")
    axes[0].set_ylabel("Time (sec)")
    axes[0].set_xticks(workers)
    axes[0].set_xticklabels(["1\n(5GB)", "2\n(10GB)"])
    axes[0].grid(axis='y')

    # compare with ideal
    axes[1].plot(workers, times, 'o-', label='Actual')
    axes[1].plot(workers, ideal, 's--', label='Ideal')
    axes[1].set_title("Runtime vs Ideal")
    axes[1].set_xlabel("Workers")
    axes[1].set_ylabel("Time (sec)")
    axes[1].set_xticks(workers)
    axes[1].set_xticklabels(["1\n(5GB)", "2\n(10GB)"])
    axes[1].legend()
    axes[1].grid()

    plt.tight_layout()
    plt.savefig("weak_scaling.png", dpi=300, bbox_inches='tight')
    plt.show()

plot_weak_scaling(results)

